sys:
  container_name: plexmediaserver
  build: .
  restart: always
  tty: true
  environment:
    - PLEX_allowedNetworks="0.0.0.0/0.0.0.0"
  volumes:
    - data:/var/lib/plexmediaserver
    - media:/media
  ports:
    - 32400:32400
