sys:
  container_name: plexmediaserver
  build: .
  restart: always
  tty: true
  environment:
    - PLEX_DlnaEnabled="1"
    - PLEX_FriendlyName="KatieKat"
  volumes:
    - ./data/Library:/var/lib/plexmediaserver/Library
    - ./data/media:/media
  ports:
    - 32400:32400
