sys:
  container_name: plexmediaserver
  build: .
  restart: always
  tty: true
  environment:
    - PLEX_disableRemoteSecurity="1"
  volumes:
    - data:/var/lib/plexmediaserver
    - media:/media
  ports:
    - 32400:32400
