version: '3'
services:
  sys:
    container_name: plexmediaserver
    image: alinuxninja/plex
    restart: always
    tty: true
    volumes:
      - plexdata:/var/lib/plexmediaserver/Library
      - ./media:/media
    ports:
      - 32400:32400
volumes:
  plexdata: {}
