sys:
  container_name: plexmediaserver
  build: .
  restart: always
  tty: true
  environment:
    - PLEX_disableRemoteSecurity="0"
  volumes:
    - data/Library:/var/lib/plexmediaserver/Library
    - media:/media
  ports:
    - 32400:32400
