#!/bin/bash

## Get Plex Info
PLEX_DL=$(cat .plex_version)
PLEX_VER=$(echo ${PLEX_DL} | awk -F "/" '{print $5}')

echo $PLEXDL $PLEXVER

## Build Container
#docker build --build-arg PLEX_DL=${PLEX_DL} -t catdeployed/plex:${PLEX_VER} -t catdeployed/plex:latest .

