#!/bin/bash

## Get Plex Info
pip install urllib
PLEX_DL=$(python scripts/plex_getlink.py)
PLEX_VER=$(echo ${PLEX_DL} | awk -F "/" '{print $5}')

## Build Container
docker build --build-arg PLEX_DL=${PLEX_DL} -t catdeployed/plex:${PLEX_VER} -t catdeployed/plex:latest .
