version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Get Plex Download URL
          command: |
            echo 'export PLEX_DL=$(docker run -v $(pwd)/scripts/plex_getlink.py:/tmp/app.py python:3.6-alpine python /tmp/app.py)' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Get Plex Version
          command: |
            echo $'export PLEX_VERSION=$(echo ${PLEX_DL} | awk -F "/" \'{print $5}\')' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: Build Plex Docker Container
          command: |
            echo -n 'Plex Download Link: '
            echo ${PLEX_DL}
            echo -n 'Plex Version: '
            echo ${PLEX_VERSION}
            docker build --build-arg PLEX_DL=${PLEX_DL} -t catdeployed/plex:${PLEX_VERSION} -t catdeployed/plex:latest .
      - run:
          name: Skip this job for Pull Requests
          command: '[[ -v CIRCLE_PR_NUMBER ]] && circleci step halt || true'
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push to Docker Hub
          command: docker push catdeployed/plex
          context: Docker Hub

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  commit:
    jobs:
      - build:
          context: Docker Hub
